[workspace]
resolver = "3"
members = ["fileio", "lib"]

[workspace.dependencies]
lib = { path = "./lib" }

clap = { version = "4.5.53", features = ["derive"] }
nix = { version = "0.30.1", features = ["fs", "process", "uio"] }
